# 运行命令
# python xdpo/run_demo.py --config xdpo/config_2.yaml --wandb_project xdpo_demo

### 定制参数
use_dynamic_beta: false
disco_pref: true

### model
model_name_or_path: /root/models/Qwen1.5-0.5B
trust_remote_code: true
# ref_model: /root/models/Qwen1.5-0.5B-Chat
# freeze_policy: true  # 启用策略模型冻结，只训练beta_head

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true  # 使用bf16精度
ddp_timeout: 180000000
resume_from_checkpoint: null


### dataset
dataset: hh_rlhf_en
dataset_dir: data
template: qwen
cutoff_len: 512
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 1 
dataloader_num_workers: 2

### output
output_dir: results/qwen15-0.5b/lora/config_2_20250322_100919
logging_steps: 5
save_steps: 100
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: [wandb]

### eval
eval_dataset: hh_rlhf_en
# val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 5 