### model
model_name_or_path: /share/new_models/Shanghai_AI_Laboratory/internlm2_5-1_8b-chat

### method
stage: toyrm
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: dpo_en_demo
template: intern2
cutoff_len: 1024
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/intern2-5-1-8b/lora/toy_reward
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500 