### model
model_name_or_path: /root/models/Qwen1.5-0.5B
trust_remote_code: true

### method
stage: foodpo
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
pref_beta: 0.1
pref_beta_scale: 0.0  # 暂时设为0以禁用动态beta功能，方便调试

### 其他参数根据我们的算法去调整


### dataset
dataset: dpo_en_demo
template: qwen
cutoff_len: 1024
max_samples: 10  # 减少样本数量以加快测试
overwrite_cache: true
preprocessing_num_workers: 4

### output
output_dir: saves/qwen1.5-0.5b/lora/foodpo_test
logging_steps: 5
save_steps: 50
plot_loss: true
overwrite_output_dir: true
report_to: []

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 1.0e-5  # 稍微增加学习率
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

## eval
val_size: 0.1
per_device_eval_batch_size: 2
eval_strategy: steps
eval_steps: 10

# 运行命令
# llamafactory-cli train examples/train_lora/qwen1_5_0_5b_lora_foodpo_test.yaml 